all:	main
		./main
		make clean

main:	.\T2-main.cpp .\dijkstra.h .\edge.h .\Grafo_dirigido.h  .\Caixa.h
		g++ -o main .\T2-main.cpp .\dijkstra.h .\edge.h .\Grafo_dirigido.h  .\Caixa.h

clean: 	
		rm main 